<section>
    ...
    <h2 class="text-lg font-medium text-gray-900 dark:text-gray-100">
        {{ __('メールアドレスを更新') }}
    </h2>
    ...
    <p class="mt-1 text-sm text-gray-600 dark:text-gray-400">
        {{ __('新しいメールアドレスを入力してください。') }}
    </p>
    ...
    <x-input-label for="email" :value="__('新しいメールアドレス')" />
    ...
    <x-input-error :messages="$errors->updateEmail->get('email')" class="mt-2" />
    ...
    <x-primary-button>{{ __('保存') }}</x-primary-button>
    ...
</section>