<section>
    ...
    <h2 class="text-lg font-medium text-gray-900 dark:text-gray-100">
        {{ __('プロフィールを更新') }}
    </h2>
    ...
    <p class="mt-1 text-sm text-gray-600 dark:text-gray-400">
        {{ __('プロフィール情報を更新してください。') }}
    </p>
    ...
    <x-input-label for="name" :value="__('名前')" />
    ...
    <x-input-error :messages="$errors->updateProfile->get('name')" class="mt-2" />
    ...
    <x-primary-button>{{ __('保存') }}</x-primary-button>
    ...
</section>